name: Trigger Blog Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-central-ssg:
    uses: Murilo-fab/another-ssg/.github/workflows/compile-and-deploy.yml@main